export const options = [
  { value: "", text: "--Select By Category--" },
  { value: "Restaurant", text: "Restaurant" },
  { value: "Bar", text: "Bar" },
  { value: "Retail", text: "Retail" },
  { value: "Salon", text: "Salon" },
  { value: "Animal", text: "Animal" },
  { value: "Auto", text: "Auto" },
  { value: "Hardware", text: "Hardware" },
  { value: "Gas Station", text: "Gas Station" },
  { value: "Health", text: "Health" },
  { value: "Accounting", text: "Accounting" },
  { value: "Airport", text: "Airport" },
  { value: "Amusement Park", text: "Amusement Park" },
  { value: "Art Gallery", text: "Art Gallery" },
  { value: "ATM", text: "ATM" },
  { value: "Bakery", text: "Bakery" },
  { value: "Bank", text: "Bank" },
  { value: "Beauty Salon", text: "Beauty Salon" },
  { value: "Church", text: "Church" },
  { value: "Cleaning", text: "Cleaning" },
  { value: "Electrician", text: "Electrician" },
  { value: "Funeral Home", text: "Funeral Home" },
  { value: "Gas Station", text: "Gas Station" },
  { value: "Gym", text: "Gym" },
  { value: "Hardware Store", text: "Hardware Store" },
  { value: "Home Goods Store", text: "Home Goods Store" },
  { value: "Hospital", text: "Hospital" },
  { value: "Insurance Agency", text: "Insurance Agency" },
  { value: "Laundry", text: "Laundry" },
  { value: "Lawyer", text: "Lawyer" },
  { value: "Library", text: "Library" },
  { value: "Locksmith", text: "Locksmith" },
  { value: "Lodging", text: "Lodging" },
  { value: "Moving Company", text: "Moving Company" },
  { value: "Painter", text: "Painter" },
  { value: "Park", text: "Park" },
  { value: "Pet Store", text: "Pet Store" },
  { value: "Pharmacy", text: "Pharmacy" },
  { value: "Plumber", text: "Plumber" },
  { value: "Police", text: "Police" },
  { value: "Post Office", text: "Post Office" },
  { value: "Real Estate Agency", text: "Real Estate Agency" },
  { value: "Roofing Contractor", text: "Roofing Contractor" },
  { value: "Shopping Mall", text: "Shopping Mall" },
  { value: "Spa", text: "Spa" },
  { value: "Storage", text: "Storage" },
  { value: "Travel Agency", text: "Travel Agency" },
  { value: "Veterinary Care", text: "Veterinary Care" },
  { value: "Other", text: "Other" },
];
