const mongoose = require("mongoose");

const businessSchema = mongoose.Schema({
  name: {
    type: String,
    required: true,
    trim: true,
  },
  description: {
    type: String,
    trim: true,
  },
  category: {
    type: String,
    required: true,
    enum: [
      "Restaurant",
      "Bar",
      "Cafe",
      "Convenience Store",
      "Retail",
      "Salon",
      "Animal",
      "Auto",
      "Hardware",
      "Gas Station",
      "Other",
      "Dentist",
      "Health",
      "Accounting",
      "Airport",
      "Amusement Park",
      "Aquarium",
      "Art Gallery",
      "ATM",
      "Bakery",
      "Bank",
      "Beauty Salon",
      "Book Store",
      "Bowling Alley",
      "Church",
      "Cleaning",
      "Electrician",
      "Funeral Home",
      "Gas Station",
      "Gym",
      "Hair Care",
      "Hardware Store",
      "Home Goods Store",
      "Hospital",
      "Insurance Agency",
      "Laundry",
      "Lawyer",
      "Library",
      "Locksmith",
      "Lodging",
      "Moving Company",
      "Painter",
      "Park",
      "Pet Store",
      "Pharmacy",
      "Physiotherapist",
      "Plumber",
      "Police",
      "Post Office",
      "Real Estate Agency",
      "Restaurant",
      "Roofing Contractor",
      "RV Park",
      "School",
      "Secondary School",
      "Shoe Store",
      "Shopping Mall",
      "Spa",
      "Storage",
      "Travel Agency",
      "Veterinary Care",
    ],
  },
  address: {
    type: String,
    required: true,
    trim: true,
  },
  phone: {
    type: String,
    required: true,
    trim: true,
  },

  website: {
    type: String,
    trim: true,
  },
  placeId: {
    type: String,
    trim: true,
  },
  photo: {
    type: String,
    trim: true,
  },
  rating: {
    type: Number,
    default: 0,
  },

  createdAt: {
    type: Date,
    default: Date.now,
  },

  reviews: [
    {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Review",
    },
  ],
});

module.exports = mongoose.model("Business", businessSchema);
